### ISSUE TITLE
"No such image"

### ISSUE THREAD

**Issue by bear454** [kubic-project/automation#142]
On a clean install of openSUSE Leap 42.3:

```
jmason@ws-jmason-02:~/projects/github/kubic-project/automation/caasp-kvm> ./caasp-kvm --build -m 1 -w 2
>>> [caasp-kvm] CaaS Platform Building
>>> [caasp-kvm] Downloading CaaSP KVM Image
 >> File on Disk  : /home/jmason/projects/github/kubic-project/automation/downloads/SUSE-CaaS-Platform-2.0-KVM-and-Xen.x86_64-2.0.0-Build7.21.qcow2
 >> Static Path : /home/jmason/projects/github/kubic-project/automation/downloads/kvm-devel
>>> [caasp-kvm] Building Velum Development Image
Downloading latest build of the velum development image
Traceback (most recent call last):
  File "./tools/../../misc-tools/download_image.py", line 224, in <module>
    use_channel_file(args)
  File "./tools/../../misc-tools/download_image.py", line 69, in use_channel_file
    remote_canonical_url = get_canonical_url(args, remote_url)
  File "./tools/../../misc-tools/download_image.py", line 122, in get_canonical_url
    return get_canonical_url(args, image.headers.get('Location'))
  File "./tools/../../misc-tools/download_image.py", line 122, in get_canonical_url
    return get_canonical_url(args, image.headers.get('Location'))
  File "./tools/../../misc-tools/download_image.py", line 119, in get_canonical_url
    image = requests.head(url, proxies=proxies)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 96, in head
    return request('head', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 495, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: hostname 'ibs-mirror.prv.suse.net' doesn't match either of '*.microfocus.net', 'microfocus.net'
Error response from daemon: No such image: sles12/velum-development:0.0
Error response from daemon: No such image: sles12/velum:development
./tools/build-velum-image.sh: line 20: $1: unbound variable
```

**Comment by robdaemon** [comment]
`requests.exceptions.SSLError: hostname 'ibs-mirror.prv.suse.net' doesn't match either of '*.microfocus.net', 'microfocus.net'`

This requires that you're connected to the SUSE R&D network.

**Comment by bear454** [comment]
Why bother open sourcing it, if it can only be used by employees on a private network?

**Comment by robdaemon** [comment]
@bear454 You are absolutely right and it's a big problem we have to address.

**Comment by kiall** [comment]
@bear454 openSUSE Kubic builds are making progress with @sysrich and @thkukuk pushing it forward, when it's ready enough, and as time allows, we'll look at what's needed from our dev tools, and what changes are needed those tools to make them work for openSUSE builds.

**Comment by bear454** [comment]
Should we close this, then?

**Comment by MalloZup** [comment]
@bear454 https://github.com/kubic-project/automation/pull/524 closing
